stages:
  - build
  - deploy

build:
  stage: build
  image: node
  script:
#    - apt update -y
#    - apt install npm -y
    - npm install
  artifacts:
    paths:
      - node_modules/
      - package.json/
      - public/

deploy:
  stage: deploy
  image: node
  script:
#    - apt update -y
#    - apt install npm -y
#    - npm install
    - npm start > /dev/null 2>&1 &
