name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Deploy Application
      run: |
        # Navigate to the deployment directory
        cd /var/www/my-node-app
        # Stop the current application using pm2
        sudo pm2 stop node-app
        # Copy the build artifacts to the deployment directory
        sudo cp -R ${{ github.workspace }}/* /var/www/my-node-app
        # Start the application using pm2 and update environment variables
        sudo pm2 restart node-app 
